dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.146.131:2181
  protocol:
    port: 28801
  consumer:
    timeout: 60000
    check: false
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v9?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
